// resources/views/reports/contribution_report.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contribution Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }
        .header h1 {
            color: #333;
            margin-bottom: 10px;
        }
        .meta-info {
            margin-bottom: 30px;
        }
        .meta-info .row {
            display: flex;
            margin-bottom: 10px;
        }
        .meta-info .label {
            font-weight: bold;
            width: 150px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
        }
        .total-row {
            font-weight: bold;
            background-color: #f8f9fa;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 2px solid #eee;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Cash Cows Sacco</h1>
            <h2>Contribution Report</h2>
        </div>
        
        <div class="meta-info">
            <div class="row">
                <span class="label">Member Name:</span>
                <span>{{ $user->name }}</span>
            </div>
            <div class="row">
                <span class="label">Email:</span>
                <span>{{ $user->email }}</span>
            </div>
            <div class="row">
                <span class="label">Report Period:</span>
                <span>{{ $startDate->format('M d, Y') }} to {{ $endDate->format('M d, Y') }}</span>
            </div>
            <div class="row">
                <span class="label">Generated On:</span>
                <span>{{ $generatedAt->format('M d, Y g:i A') }}</span>
            </div>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                @forelse($contributions as $contribution)
                    <tr>
                        <td>{{ Carbon\Carbon::parse($contribution->transaction_date)->format('M d, Y') }}</td>
                        <td>KES {{ number_format($contribution->amount, 2) }}</td>
                        <td>{{ $contribution->description ?: 'N/A' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" style="text-align: center; padding: 20px;">No contributions found for this period</td>
                    </tr>
                @endforelse
                
                @if($contributions->isNotEmpty())
                    <tr class="total-row">
                        <td>Total</td>
                        <td>KES {{ number_format($totalAmount, 2) }}</td>
                        <td></td>
                    </tr>
                @endif
            </tbody>
        </table>
        
        <div class="footer">
            <p>This is an official report generated by Cash Cows Sacco Management System</p>
            <p>{{ $generatedAt->format('Y-m-d H:i:s') }}</p>
        </div>
    </div>
</body>
</html>